package br.com.sulamerica.dm.movvida.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MovimentacaoExclusao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Data de Exclusao")
	private java.time.LocalDate dataExclusao;
	@org.kie.api.definition.type.Label("Código do Motivo da Exclusão")
	private int codigoMotivo;

	@org.kie.api.definition.type.Label("Lista de datas de Exclusao válidas")
	private java.util.List<java.time.LocalDate> dataExclusaoValidaList;

	@org.kie.api.definition.type.Label("O período permitido para data de exclusão a partir de hoje em dias")
	private int periodoPermitidoExclusaoEmDias;

	@org.kie.api.definition.type.Label("Se permitir Data de Exclusão Retroativa")
	private boolean permitirExclusaoRetroativa;

	@org.kie.api.definition.type.Label("Se a Data Exclusão for válida ou não")
	private boolean dataExclusaoValida;

	@org.kie.api.definition.type.Label("periodo Permitido Exclusao Em Dias RN412")
	private int periodoPermitidoExclusaoEmDiasRN412;

	@org.kie.api.definition.type.Label("Data Exclusao Valida RN412")
	private boolean dataExclusaoValidaRN412;

	@org.kie.api.definition.type.Label("Data Exclusao Valida RN412 List")
	private java.util.List<java.time.LocalDate> dataExclusaoValidaRN412List;

	@org.kie.api.definition.type.Label("Datas Uteis RN412")
	private java.util.List<java.time.LocalDate> datasUteisRN412;

	@org.kie.api.definition.type.Label("Periodo Permitido Exclusao Em Dias Obito")
	private int periodoPermitidoExclusaoEmDiasObito;

	@org.kie.api.definition.type.Label("Data Exclusao Valida Obito")
	private boolean dataExclusaoValidaObito;

	@org.kie.api.definition.type.Label("Data Exclusao Valida Obito")
	private java.util.List<java.time.LocalDate> dataExclusaoValidaObitoList;

	@org.kie.api.definition.type.Label("Data Obito Retroativa")
	private boolean dataObitoRetroativa;

	@org.kie.api.definition.type.Label(value = "Data Obito Futura")
	private boolean dataObitoFutura;

	public MovimentacaoExclusao() {
	}

	public java.time.LocalDate getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(java.time.LocalDate dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	public int getCodigoMotivo() {
		return this.codigoMotivo;
	}

	public void setCodigoMotivo(int codigoMotivo) {
		this.codigoMotivo = codigoMotivo;
	}

	public java.util.List<java.time.LocalDate> getDataExclusaoValidaList() {
		return this.dataExclusaoValidaList;
	}

	public void setDataExclusaoValidaList(
			java.util.List<java.time.LocalDate> dataExclusaoValidaList) {
		this.dataExclusaoValidaList = dataExclusaoValidaList;
	}

	public int getPeriodoPermitidoExclusaoEmDias() {
		return this.periodoPermitidoExclusaoEmDias;
	}

	public void setPeriodoPermitidoExclusaoEmDias(
			int periodoPermitidoExclusaoEmDias) {
		this.periodoPermitidoExclusaoEmDias = periodoPermitidoExclusaoEmDias;
	}

	public boolean isPermitirExclusaoRetroativa() {
		return this.permitirExclusaoRetroativa;
	}

	public void setPermitirExclusaoRetroativa(boolean permitirExclusaoRetroativa) {
		this.permitirExclusaoRetroativa = permitirExclusaoRetroativa;
	}

	public boolean isDataExclusaoValida() {
		return this.dataExclusaoValida;
	}

	public void setDataExclusaoValida(boolean dataExclusaoValida) {
		this.dataExclusaoValida = dataExclusaoValida;
	}

	public int getPeriodoPermitidoExclusaoEmDiasRN412() {
		return this.periodoPermitidoExclusaoEmDiasRN412;
	}

	public void setPeriodoPermitidoExclusaoEmDiasRN412(
			int periodoPermitidoExclusaoEmDiasRN412) {
		this.periodoPermitidoExclusaoEmDiasRN412 = periodoPermitidoExclusaoEmDiasRN412;
	}

	public boolean isDataExclusaoValidaRN412() {
		return this.dataExclusaoValidaRN412;
	}

	public void setDataExclusaoValidaRN412(boolean dataExclusaoValidaRN412) {
		this.dataExclusaoValidaRN412 = dataExclusaoValidaRN412;
	}

	public java.util.List<java.time.LocalDate> getDataExclusaoValidaRN412List() {
		return this.dataExclusaoValidaRN412List;
	}

	public void setDataExclusaoValidaRN412List(
			java.util.List<java.time.LocalDate> dataExclusaoValidaRN412List) {
		this.dataExclusaoValidaRN412List = dataExclusaoValidaRN412List;
	}

	public java.util.List<java.time.LocalDate> getDatasUteisRN412() {
		return this.datasUteisRN412;
	}

	public void setDatasUteisRN412(
			java.util.List<java.time.LocalDate> datasUteisRN412) {
		this.datasUteisRN412 = datasUteisRN412;
	}

	public int getPeriodoPermitidoExclusaoEmDiasObito() {
		return this.periodoPermitidoExclusaoEmDiasObito;
	}

	public void setPeriodoPermitidoExclusaoEmDiasObito(
			int periodoPermitidoExclusaoEmDiasObito) {
		this.periodoPermitidoExclusaoEmDiasObito = periodoPermitidoExclusaoEmDiasObito;
	}

	public boolean isDataExclusaoValidaObito() {
		return this.dataExclusaoValidaObito;
	}

	public void setDataExclusaoValidaObito(boolean dataExclusaoValidaObito) {
		this.dataExclusaoValidaObito = dataExclusaoValidaObito;
	}

	public java.util.List<java.time.LocalDate> getDataExclusaoValidaObitoList() {
		return this.dataExclusaoValidaObitoList;
	}

	public void setDataExclusaoValidaObitoList(
			java.util.List<java.time.LocalDate> dataExclusaoValidaObitoList) {
		this.dataExclusaoValidaObitoList = dataExclusaoValidaObitoList;
	}

	public boolean isDataObitoRetroativa() {
		return this.dataObitoRetroativa;
	}

	public void setDataObitoRetroativa(boolean dataObitoRetroativa) {
		this.dataObitoRetroativa = dataObitoRetroativa;
	}

	public boolean isDataObitoFutura() {
		return this.dataObitoFutura;
	}

	public void setDataObitoFutura(boolean dataObitoFutura) {
		this.dataObitoFutura = dataObitoFutura;
	}

	public MovimentacaoExclusao(java.time.LocalDate dataExclusao,
			int codigoMotivo,
			java.util.List<java.time.LocalDate> dataExclusaoValidaList,
			int periodoPermitidoExclusaoEmDias,
			boolean permitirExclusaoRetroativa, boolean dataExclusaoValida,
			int periodoPermitidoExclusaoEmDiasRN412,
			boolean dataExclusaoValidaRN412,
			java.util.List<java.time.LocalDate> dataExclusaoValidaRN412List,
			java.util.List<java.time.LocalDate> datasUteisRN412,
			int periodoPermitidoExclusaoEmDiasObito,
			boolean dataExclusaoValidaObito,
			java.util.List<java.time.LocalDate> dataExclusaoValidaObitoList,
			boolean dataObitoRetroativa, boolean dataObitoFutura) {
		this.dataExclusao = dataExclusao;
		this.codigoMotivo = codigoMotivo;
		this.dataExclusaoValidaList = dataExclusaoValidaList;
		this.periodoPermitidoExclusaoEmDias = periodoPermitidoExclusaoEmDias;
		this.permitirExclusaoRetroativa = permitirExclusaoRetroativa;
		this.dataExclusaoValida = dataExclusaoValida;
		this.periodoPermitidoExclusaoEmDiasRN412 = periodoPermitidoExclusaoEmDiasRN412;
		this.dataExclusaoValidaRN412 = dataExclusaoValidaRN412;
		this.dataExclusaoValidaRN412List = dataExclusaoValidaRN412List;
		this.datasUteisRN412 = datasUteisRN412;
		this.periodoPermitidoExclusaoEmDiasObito = periodoPermitidoExclusaoEmDiasObito;
		this.dataExclusaoValidaObito = dataExclusaoValidaObito;
		this.dataExclusaoValidaObitoList = dataExclusaoValidaObitoList;
		this.dataObitoRetroativa = dataObitoRetroativa;
		this.dataObitoFutura = dataObitoFutura;
	}

}