package br.com.sulamerica.dm.movvida.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MovimentacaoTransferenciaEmpresa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Empresa de Destino")
	private java.lang.String empresaDestino;

	@org.kie.api.definition.type.Label(value = "Codigo plano Destino")
	private java.lang.String codigoPlanoDestino;

	@org.kie.api.definition.type.Label(value = "Plano Alterado")
	private boolean planoAlterado;

	@org.kie.api.definition.type.Label(value = "codigo de local destino")
	private java.lang.String codigoLocalDestino;

	public MovimentacaoTransferenciaEmpresa() {
	}

	public java.lang.String getEmpresaDestino() {
		return this.empresaDestino;
	}

	public void setEmpresaDestino(java.lang.String empresaDestino) {
		this.empresaDestino = empresaDestino;
	}

	public java.lang.String getCodigoPlanoDestino() {
		return this.codigoPlanoDestino;
	}

	public void setCodigoPlanoDestino(java.lang.String codigoPlanoDestino) {
		this.codigoPlanoDestino = codigoPlanoDestino;
	}

	public boolean isPlanoAlterado() {
		return this.planoAlterado;
	}

	public void setPlanoAlterado(boolean planoAlterado) {
		this.planoAlterado = planoAlterado;
	}

	public java.lang.String getCodigoLocalDestino() {
		return this.codigoLocalDestino;
	}

	public void setCodigoLocalDestino(java.lang.String codigoLocalDestino) {
		this.codigoLocalDestino = codigoLocalDestino;
	}

	public MovimentacaoTransferenciaEmpresa(java.lang.String empresaDestino,
			java.lang.String codigoPlanoDestino, boolean planoAlterado,
			java.lang.String codigoLocalDestino) {
		this.empresaDestino = empresaDestino;
		this.codigoPlanoDestino = codigoPlanoDestino;
		this.planoAlterado = planoAlterado;
		this.codigoLocalDestino = codigoLocalDestino;
	}

}