package br.com.sulamerica.dm.movvida.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Response implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Mensagem")
	private java.lang.String mensagem;
	@org.kie.api.definition.type.Label("Tipo de Mensagem (C ou E)")
	private String tipoMensagem;

	@org.kie.api.definition.type.Label("Código de Mensagem")
	private java.lang.String codigo;

	public Response() {
	}

	public java.lang.String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(java.lang.String mensagem) {
		this.mensagem = mensagem;
	}

	public java.lang.String getTipoMensagem() {
		return this.tipoMensagem;
	}

	public void setTipoMensagem(java.lang.String tipoMensagem) {
		this.tipoMensagem = tipoMensagem;
	}

	public java.lang.String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.String codigo) {
		this.codigo = codigo;
	}

	public Response(java.lang.String mensagem, java.lang.String tipoMensagem,
			java.lang.String codigo) {
		this.mensagem = mensagem;
		this.tipoMensagem = tipoMensagem;
		this.codigo = codigo;
	}

}