package br.com.sulamerica.dm.movvida.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MovimentacaoReabertura implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Qtde de dias que o beneficiario foi excluido")
	private int diasBeneficiarioExcluido;

	public MovimentacaoReabertura() {
	}

	public int getDiasBeneficiarioExcluido() {
		return this.diasBeneficiarioExcluido;
	}

	public void setDiasBeneficiarioExcluido(int diasBeneficiarioExcluido) {
		this.diasBeneficiarioExcluido = diasBeneficiarioExcluido;
	}

	public MovimentacaoReabertura(int diasBeneficiarioExcluido) {
		this.diasBeneficiarioExcluido = diasBeneficiarioExcluido;
	}

}