package br.com.sulamerica.dm.movvida.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MovimentacaoAlteracaoPlano implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Data de Alteração Plano")
	private java.time.LocalDate dataAlteracaoPlano;

	@org.kie.api.definition.type.Label("Lista de datas de Alteração Plano válidas")
	private java.util.List<java.time.LocalDate> dataAlteracaoPlanoValidaList;

	@org.kie.api.definition.type.Label("O período permitido para data de alteração de plano a partir de hoje em dias")
	private int periodoPermitidoAposImplantacaoEmDias;

	@org.kie.api.definition.type.Label("O período permitido para registrar a movimetação a partir da data de alteração plano em dias")
	private int periodoPermitidoRegMovAlteracaoPlano;

	@org.kie.api.definition.type.Label("Se a Data Alteração Plano for válida ou não")
	private boolean dataAlteracaoPlanoValida;

	@org.kie.api.definition.type.Label("Permite alteração de plano a qualquer momento")
	private boolean permiteAlteracaoPlanoQualquerMomento;

	@org.kie.api.definition.type.Label(value = "Se a empresa foi implantada recentemente")
	private boolean empresaRecemImplantada;

	public MovimentacaoAlteracaoPlano() {
	}

	public java.time.LocalDate getDataAlteracaoPlano() {
		return this.dataAlteracaoPlano;
	}

	public void setDataAlteracaoPlano(java.time.LocalDate dataAlteracaoPlano) {
		this.dataAlteracaoPlano = dataAlteracaoPlano;
	}

	public java.util.List<java.time.LocalDate> getDataAlteracaoPlanoValidaList() {
		return this.dataAlteracaoPlanoValidaList;
	}

	public void setDataAlteracaoPlanoValidaList(
			java.util.List<java.time.LocalDate> dataAlteracaoPlanoValidaList) {
		this.dataAlteracaoPlanoValidaList = dataAlteracaoPlanoValidaList;
	}

	public int getPeriodoPermitidoAposImplantacaoEmDias() {
		return this.periodoPermitidoAposImplantacaoEmDias;
	}

	public void setPeriodoPermitidoAposImplantacaoEmDias(
			int periodoPermitidoAposImplantacaoEmDias) {
		this.periodoPermitidoAposImplantacaoEmDias = periodoPermitidoAposImplantacaoEmDias;
	}

	public int getPeriodoPermitidoRegMovAlteracaoPlano() {
		return this.periodoPermitidoRegMovAlteracaoPlano;
	}

	public void setPeriodoPermitidoRegMovAlteracaoPlano(
			int periodoPermitidoRegMovAlteracaoPlano) {
		this.periodoPermitidoRegMovAlteracaoPlano = periodoPermitidoRegMovAlteracaoPlano;
	}

	public boolean isDataAlteracaoPlanoValida() {
		return this.dataAlteracaoPlanoValida;
	}

	public void setDataAlteracaoPlanoValida(boolean dataAlteracaoPlanoValida) {
		this.dataAlteracaoPlanoValida = dataAlteracaoPlanoValida;
	}

	public boolean isPermiteAlteracaoPlanoQualquerMomento() {
		return this.permiteAlteracaoPlanoQualquerMomento;
	}

	public void setPermiteAlteracaoPlanoQualquerMomento(
			boolean permiteAlteracaoPlanoQualquerMomento) {
		this.permiteAlteracaoPlanoQualquerMomento = permiteAlteracaoPlanoQualquerMomento;
	}

	public boolean isEmpresaRecemImplantada() {
		return this.empresaRecemImplantada;
	}

	public void setEmpresaRecemImplantada(boolean empresaRecemImplantada) {
		this.empresaRecemImplantada = empresaRecemImplantada;
	}

	public MovimentacaoAlteracaoPlano(java.time.LocalDate dataAlteracaoPlano,
			java.util.List<java.time.LocalDate> dataAlteracaoPlanoValidaList,
			int periodoPermitidoAposImplantacaoEmDias,
			int periodoPermitidoRegMovAlteracaoPlano,
			boolean dataAlteracaoPlanoValida,
			boolean permiteAlteracaoPlanoQualquerMomento,
			boolean empresaRecemImplantada) {
		this.dataAlteracaoPlano = dataAlteracaoPlano;
		this.dataAlteracaoPlanoValidaList = dataAlteracaoPlanoValidaList;
		this.periodoPermitidoAposImplantacaoEmDias = periodoPermitidoAposImplantacaoEmDias;
		this.periodoPermitidoRegMovAlteracaoPlano = periodoPermitidoRegMovAlteracaoPlano;
		this.dataAlteracaoPlanoValida = dataAlteracaoPlanoValida;
		this.permiteAlteracaoPlanoQualquerMomento = permiteAlteracaoPlanoQualquerMomento;
		this.empresaRecemImplantada = empresaRecemImplantada;
	}

}